# Generated by Django 3.2.16 on 2022-11-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saled',
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='estoque.inventory'),
        ),
    ]
