# Generated by Django 3.2.16 on 2022-11-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_order_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='total_vendas',
        ),
        migrations.AddField(
            model_name='company',
            name='faturamento_total',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='faturamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='situation',
            field=models.CharField(blank=True, choices=[('aprovada', 'Approved'), ('rejeitada', 'Rejected'), ('pendente', 'Pending')], default='pendente', max_length=15, verbose_name='situation'),
        ),
    ]
