# Generated by Django 3.2.16 on 2022-11-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20221123_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='pruduct',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='estoque.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tipo',
            field=models.CharField(blank=True, choices=[('genérico', 'Generico'), ('roupas', 'Clothing'), ('comida', 'Food'), ('rémedio', 'Drug')], max_length=10, null=True),
        ),
    ]
