# Generated by Django 3.2.16 on 2022-11-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_auto_20221124_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='pruduct',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='estoque.empresa'),
        ),
    ]
