# Generated by Django 3.2.16 on 2022-11-24 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0007_auto_20221124_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='registry',
        ),
        migrations.AddField(
            model_name='order',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='estoque.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='faturamento_total',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='faturamento total'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
