# Generated by Django 3.2.16 on 2022-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_auto_20221124_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='type',
            field=models.CharField(choices=[('mercado', 'Market'), ('outro', 'Other')], default='mercado', max_length=20),
        ),
    ]
