# Generated by Django 3.2.16 on 2022-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_empresa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_product',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
