# Generated by Django 3.2.16 on 2022-11-24 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_order_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_product',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
