# Generated by Django 3.2.16 on 2022-12-02 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('total_billing', models.FloatField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('price', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('product_type', models.CharField(choices=[('generic', 'Generic'), ('food', 'Food'), ('drug', 'Drug'), ('other', 'Other')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('product_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('situation', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejjected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15, verbose_name='situation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='quantity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='empresa.product')),
            ],
        ),
    ]
