# Generated by Django 3.2.16 on 2022-11-23 01:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('total_vendas', models.PositiveIntegerField(blank=True, default=0, verbose_name='total vendas')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invetorys', to='estoque.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boughtAt', models.DateTimeField(auto_now_add=True, verbose_name='bought at')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='estoque.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('saled', models.BooleanField(blank=True, default=False, verbose_name='saled')),
                ('tipo', models.CharField(choices=[('genérico', 'Generico'), ('roupas', 'Clothing'), ('comida', 'Food'), ('rémedio', 'Drug')], max_length=10, null=True)),
                ('fabricatedAt', models.DateField(verbose_name='fabricated at')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='estoque.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='estoque.product')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='estoque.sale')),
            ],
        ),
    ]
