# Generated by Django 3.2.16 on 2022-11-29 19:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='product_price',
            field=models.FloatField(default=11, validators=[django.core.validators.MinValueValidator(0.1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
