# Generated by Django 3.2.16 on 2022-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20221123_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='situation',
            field=models.CharField(blank=True, choices=[('aprovada', 'Approved'), ('fechada', 'Closed'), ('pendente', 'Pending')], default='pendente', max_length=15, verbose_name='situation'),
        ),
    ]
