# Generated by Django 3.2.16 on 2022-12-04 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='product_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
