# Generated by Django 3.2.16 on 2022-11-23 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0004_auto_20221123_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('faturamento_total', models.PositiveIntegerField(blank=True, default=0, verbose_name='faturamento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invetorys', to='estoque.empresa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='estoque.empresa'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
