# Generated by Django 3.2.16 on 2022-12-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20221204_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.company'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.company'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.product'),
        ),
    ]
